<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_BELI_product-image-photo lazyloaded</name>
   <tag></tag>
   <elementGuidId>3ea2942d-1eec-4d1a-8f84-c923eddd4c14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='amasty-shopby-product-list']/div[3]/ol/li[2]/div/a/span/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9f5933f9-597b-4335-8fb7-f06f792693ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-image-photo lazyloaded</value>
      <webElementGuid>b6bbd967-dfbe-4a16-9e56-1e778e4897b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.matahari.com/media/catalog/product/4/1/41459734_1.jpg?optimize=medium&amp;fit=bounds&amp;height=379&amp;width=293</value>
      <webElementGuid>2ec01bd2-5e12-46a0-a499-80c6ab81c4c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://www.matahari.com/media/catalog/product/4/1/41459734_1.jpg?optimize=medium&amp;fit=bounds&amp;height=379&amp;width=293</value>
      <webElementGuid>4649aedf-9cec-4c5e-bdcc-3a7bec517329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max-width</name>
      <type>Main</type>
      <value>293</value>
      <webElementGuid>aa3483c1-f467-484c-9657-330a0d4b7d31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max-height</name>
      <type>Main</type>
      <value>379</value>
      <webElementGuid>dba77baa-6602-4cce-b28b-ba550eed3955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>St. Yves Ballerinas Ribbon Women</value>
      <webElementGuid>4df630e0-fbc9-408e-b48d-689b818aa486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;amasty-shopby-product-list&quot;)/div[@class=&quot;products wrapper grid products-grid&quot;]/ol[@class=&quot;products list items product-items&quot;]/li[@class=&quot;item product product-item&quot;]/div[@class=&quot;product-item-info&quot;]/a[@class=&quot;product photo product-item-photo product-item-click&quot;]/span[@class=&quot;product-image-container&quot;]/span[@class=&quot;product-image-wrapper&quot;]/img[@class=&quot;product-image-photo lazyloaded&quot;]</value>
      <webElementGuid>711060be-a969-43eb-aac1-12645a73c96b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='amasty-shopby-product-list']/div[3]/ol/li[2]/div/a/span/span/img</value>
      <webElementGuid>10bab896-5c94-4cf5-800d-e6d72d2e995d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='St. Yves Ballerinas Ribbon Women']</value>
      <webElementGuid>e9d30f9c-9831-4c57-bd25-b5b75f2c943f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/a/span/span/img</value>
      <webElementGuid>9bf6447a-96a6-4fb9-a505-85b8d274eb0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.matahari.com/media/catalog/product/4/1/41459734_1.jpg?optimize=medium&amp;fit=bounds&amp;height=379&amp;width=293' and @alt = 'St. Yves Ballerinas Ribbon Women']</value>
      <webElementGuid>cd7bada8-5883-49ca-886d-e187d5fb9e14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
