<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Hapus item</name>
   <tag></tag>
   <elementGuidId>72594fcc-33fc-4180-9c8f-edcbb11a07b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='shopping-cart-table']/tbody/tr/td/div/div[2]/div[2]/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.action.action-delete.mthr-remove-from-cart</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fa8b2208-558c-4087-af0a-49e60041c6b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>f495faf2-451d-4b00-927d-775280453d12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Hapus item</value>
      <webElementGuid>e95af158-f31a-4603-afbf-da3d1ec13b93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>action action-delete mthr-remove-from-cart</value>
      <webElementGuid>4b8418fc-c281-43ea-838f-79f352581c3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm</name>
      <type>Main</type>
      <value>{&quot;name&quot;:&quot;St. Yves Ballerinas Ribbon Women&quot;,&quot;id&quot;:&quot;41459654&quot;,&quot;price&quot;:100000,&quot;brand&quot;:&quot;ST. YVES&quot;,&quot;category&quot;:[&quot;promo\/jumbo\/hemat-hingga-45-35-25\/sepatu&quot;,&quot;promo\/promo-brand\/st-yves-diskon-hingga-70\/sepatu&quot;,&quot;promo\/penawaran-spesial\/top-selling-spesial-hemat-hingga-80\/sepatu&quot;,&quot;promo\/jumbo\/cole-connexion-st-yves-little-m-diskon-mulai-dari-20\/sepatu&quot;,&quot;promo\/promo-brand\/st-yves-diskon-hingga-65\/sepatu&quot;,&quot;promo\/penawaran-spesial\/alas-kaki-terlaris-hemat-hingga-80\/sepatu&quot;,&quot;promo\/promo-brand\/st-yves-diskon-hingga-60\/sepatu&quot;,&quot;promo\/jumbo\/top-selling-spesial-hemat-hingga-80\/sepatu&quot;,&quot;promo\/promo-minggu-ini\/sepatu-favoritmu-diskon-hingga-40-ekstra-35\/sepatu&quot;,&quot;promo\/3-3-generasi-keren\/siapkan-gaya-ramadan-hemat-hingga-70\/sepatu&quot;,&quot;promo\/3-3-generasi-keren\/st-yves-hemat-hingga-60\/wanita&quot;,&quot;promo\/penawaran-spesial\/kejar-diskon-sepatu-diskon-hingga-45-ekstra-25\/sepatu&quot;,&quot;promo\/3-3-generasi-keren\/kerennya-produk-lokal-mulai-dari-33-000\/sepatu&quot;,&quot;promo\/penawaran-khusus\/sepatu\/st-yves-hemat-hingga-60&quot;,&quot;promo\/promo-brand\/st-yves-diskon-hingga-70\/wanita&quot;,&quot;promo\/clearance-sale\/clearance-sale-sepatu&quot;,&quot;sepatu\/wanita\/sepatu-flat&quot;,&quot;promo\/3-3-generasi-keren\/1-1-aku-tetap-untung-extra-23&quot;,&quot;promo\/3-3-generasi-keren\/st-yves-hemat-hingga-65&quot;,&quot;promo\/promo-brand-sepatu\/st-yves-diskon-hingga-70&quot;,&quot;promo\/jumbo\/everyday-comfort-extra-15&quot;,&quot;wanita\/sepatu\/sepatu-flat&quot;,&quot;promo\/jumbo\/weekend-surprise-deals-extra-40&quot;,&quot;promo\/promo-minggu-ini\/koleksi-alas-kaki-wanita-nevada-dan-st-yves&quot;,&quot;promo\/3-3-generasi-keren\/promo-spesial-3-3-serba-100-ribu&quot;,&quot;flash-sale-deals\/cole-connexion-details-nevada-st-yves-extra-40&quot;,&quot;brands\/st-yves&quot;,&quot;flash-sale-deals\/cole-connexion-details-nevada-st-yves-extra-45&quot;,&quot;exclude\/sepatu-tas&quot;,&quot;branded-sale\/anak&quot;,&quot;branded-sale\/sepatu&quot;],&quot;variant&quot;:&quot;37&quot;,&quot;dimension1&quot;:&quot;BLACK&quot;,&quot;metric1&quot;:79900,&quot;metric2&quot;:0,&quot;coupon&quot;:&quot;Not Available&quot;,&quot;quantity&quot;:1,&quot;item_category2&quot;:&quot;37&quot;,&quot;item_category3&quot;:&quot;BLACK&quot;,&quot;discount&quot;:79900}</value>
      <webElementGuid>bafacbe2-43a8-4352-97c3-9b80e6f31ca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-post</name>
      <type>Main</type>
      <value>{&quot;action&quot;:&quot;https:\/\/www.matahari.com\/checkout\/cart\/delete\/&quot;,&quot;data&quot;:{&quot;id&quot;:&quot;56767555&quot;,&quot;uenc&quot;:&quot;aHR0cHM6Ly93d3cubWF0YWhhcmkuY29tL2NoZWNrb3V0L2NhcnQv&quot;,&quot;confirmation&quot;:true,&quot;confirmationMessage&quot;:&quot;Apakah Kamu yakin mau menghapus produk ini dari keranjang?&quot;,&quot;remover_cart&quot;:&quot;{\&quot;name\&quot;:\&quot;St. Yves Ballerinas Ribbon Women\&quot;,\&quot;id\&quot;:\&quot;41459654\&quot;,\&quot;price\&quot;:100000,\&quot;brand\&quot;:\&quot;ST. YVES\&quot;,\&quot;category\&quot;:[\&quot;promo\\\/jumbo\\\/hemat-hingga-45-35-25\\\/sepatu\&quot;,\&quot;promo\\\/promo-brand\\\/st-yves-diskon-hingga-70\\\/sepatu\&quot;,\&quot;promo\\\/penawaran-spesial\\\/top-selling-spesial-hemat-hingga-80\\\/sepatu\&quot;,\&quot;promo\\\/jumbo\\\/cole-connexion-st-yves-little-m-diskon-mulai-dari-20\\\/sepatu\&quot;,\&quot;promo\\\/promo-brand\\\/st-yves-diskon-hingga-65\\\/sepatu\&quot;,\&quot;promo\\\/penawaran-spesial\\\/alas-kaki-terlaris-hemat-hingga-80\\\/sepatu\&quot;,\&quot;promo\\\/promo-brand\\\/st-yves-diskon-hingga-60\\\/sepatu\&quot;,\&quot;promo\\\/jumbo\\\/top-selling-spesial-hemat-hingga-80\\\/sepatu\&quot;,\&quot;promo\\\/promo-minggu-ini\\\/sepatu-favoritmu-diskon-hingga-40-ekstra-35\\\/sepatu\&quot;,\&quot;promo\\\/3-3-generasi-keren\\\/siapkan-gaya-ramadan-hemat-hingga-70\\\/sepatu\&quot;,\&quot;promo\\\/3-3-generasi-keren\\\/st-yves-hemat-hingga-60\\\/wanita\&quot;,\&quot;promo\\\/penawaran-spesial\\\/kejar-diskon-sepatu-diskon-hingga-45-ekstra-25\\\/sepatu\&quot;,\&quot;promo\\\/3-3-generasi-keren\\\/kerennya-produk-lokal-mulai-dari-33-000\\\/sepatu\&quot;,\&quot;promo\\\/penawaran-khusus\\\/sepatu\\\/st-yves-hemat-hingga-60\&quot;,\&quot;promo\\\/promo-brand\\\/st-yves-diskon-hingga-70\\\/wanita\&quot;,\&quot;promo\\\/clearance-sale\\\/clearance-sale-sepatu\&quot;,\&quot;sepatu\\\/wanita\\\/sepatu-flat\&quot;,\&quot;promo\\\/3-3-generasi-keren\\\/1-1-aku-tetap-untung-extra-23\&quot;,\&quot;promo\\\/3-3-generasi-keren\\\/st-yves-hemat-hingga-65\&quot;,\&quot;promo\\\/promo-brand-sepatu\\\/st-yves-diskon-hingga-70\&quot;,\&quot;promo\\\/jumbo\\\/everyday-comfort-extra-15\&quot;,\&quot;wanita\\\/sepatu\\\/sepatu-flat\&quot;,\&quot;promo\\\/jumbo\\\/weekend-surprise-deals-extra-40\&quot;,\&quot;promo\\\/promo-minggu-ini\\\/koleksi-alas-kaki-wanita-nevada-dan-st-yves\&quot;,\&quot;promo\\\/3-3-generasi-keren\\\/promo-spesial-3-3-serba-100-ribu\&quot;,\&quot;flash-sale-deals\\\/cole-connexion-details-nevada-st-yves-extra-40\&quot;,\&quot;brands\\\/st-yves\&quot;,\&quot;flash-sale-deals\\\/cole-connexion-details-nevada-st-yves-extra-45\&quot;,\&quot;exclude\\\/sepatu-tas\&quot;,\&quot;branded-sale\\\/anak\&quot;,\&quot;branded-sale\\\/sepatu\&quot;],\&quot;variant\&quot;:\&quot;37\&quot;,\&quot;dimension1\&quot;:\&quot;BLACK\&quot;,\&quot;metric1\&quot;:79900,\&quot;metric2\&quot;:0,\&quot;coupon\&quot;:\&quot;Not Available\&quot;,\&quot;quantity\&quot;:1,\&quot;item_category2\&quot;:\&quot;37\&quot;,\&quot;item_category3\&quot;:\&quot;BLACK\&quot;,\&quot;discount\&quot;:79900}&quot;}}</value>
      <webElementGuid>da534067-34a9-4d44-870e-c131c99bf105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Hapus item</value>
      <webElementGuid>47c328e4-6bb3-41b7-820d-1a98ae283c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopping-cart-table&quot;)/tbody[@class=&quot;cart item  last-of-group&quot;]/tr[@class=&quot;item-info&quot;]/td[@class=&quot;col item&quot;]/div[@class=&quot;product-item-details&quot;]/div[@class=&quot;cart-actions&quot;]/div[@class=&quot;col qty&quot;]/div[@class=&quot;field qty&quot;]/div[@class=&quot;bottom-tool-box&quot;]/a[@class=&quot;action action-delete mthr-remove-from-cart&quot;]</value>
      <webElementGuid>9c086d85-e51a-4cec-b676-14b5ba1951a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='shopping-cart-table']/tbody/tr/td/div/div[2]/div[2]/div/div/a</value>
      <webElementGuid>b24498fb-ae82-422f-9d21-c562203de1c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 179.900'])[3]/following::a[1]</value>
      <webElementGuid>0cd24bdf-ae62-4dc6-9578-640d275f22f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OFF'])[2]/following::a[1]</value>
      <webElementGuid>2dd72f80-2ae6-48c9-9730-a05f846f4ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='barang'])[2]/preceding::a[1]</value>
      <webElementGuid>4ae455b0-8141-412f-9e54-f8aaf1499d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[13]</value>
      <webElementGuid>df894ba6-72c1-44d6-8c54-d84c8027ae91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/a</value>
      <webElementGuid>bd2ec305-988c-4fdb-a120-7b9418fc6752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @title = 'Hapus item' and (text() = ' Hapus item' or . = ' Hapus item')]</value>
      <webElementGuid>b5cfc84e-a27e-46ee-8701-11d67f728484</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
