<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Search_svg-mthr-users-profile</name>
   <tag></tag>
   <elementGuidId>02bef831-fd79-4b06-8364-8476c2dc8c98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='html-body']/div[3]/header/div[2]/div[6]/div/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.svg-mthr-users-profile</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f09d82a9-c44c-4396-85ad-a09d20f275e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svg-mthr-users-profile</value>
      <webElementGuid>41df7337-0801-4343-b0f7-696718e40407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;html-body&quot;)/div[@class=&quot;page-wrapper&quot;]/header[@class=&quot;page-header&quot;]/div[@class=&quot;header content&quot;]/div[@class=&quot;icon-link profil&quot;]/div[1]/a[@class=&quot;navbar-link authorization-link&quot;]/span[@class=&quot;svg-mthr-users-profile&quot;]</value>
      <webElementGuid>6e9b635b-971d-45ce-91ea-51fc15e33586</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='html-body']/div[3]/header/div[2]/div[6]/div/a/span</value>
      <webElementGuid>6e22ab4d-9057-467d-b307-679ca58f609d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/a/span</value>
      <webElementGuid>cf5b3757-72a2-411e-9203-ffd080793410</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
